spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bank_app;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  jpa:
    database: h2
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8080
  servlet:
    context-path: /

account:
  record:
    pagesize: 20

endpoint:
  account: /account
  authentication: /authentication